
project_id = "jwlaydruiivvrrddkvjq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge_runtime]
enabled = true
port = 54327

# Настройки новых функций
[functions.notify_speaker_secretpoint]
verify_jwt = false

[functions.register_user_secretpoint]
verify_jwt = false

# Общие переменные окружения для всех функций
[functions.env]
# Supabase
SUPABASE_URL = "https://jwlaydruiivvrrddkvjq.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3bGF5ZHJ1aWl2dnJyZGRrdmpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTQ4MzUsImV4cCI6MjA2Mzk5MDgzNX0.8t6pjn4p7TbPpxXZwnR1GVCPQtmGUyo_HQ3Irdk9m38"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVHsiInJlZiI6Imp3bGF5ZHJ1aWl2dnJyZGRrdmpxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODQxNDgzNSwiZXhwIjoyMDYzOTkwODM1fQ.KJafEUjlyi1zWAWpKY3NFR_d-o_V8GLf3SAFyY_B4IQ"

# Telegram Bot (новое название секрета)
BOT_TOKEN_SECRETPOINT = "8001709362:AAEemeq8ZA4F1sBHaGBl2Um32lHhBOihl0k"
