// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwlaydruiivvrrddkvjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3bGF5ZHJ1aWl2dnJyZGRrdmpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTQ4MzUsImV4cCI6MjA2Mzk5MDgzNX0.8t6pjn4p7TbPpxXZwnR1GVCPQtmGUyo_HQ3Irdk9m38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);